apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsqlinstances.azure.dbaas.upbound.io
  labels:
    provider: azure
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: dbaas.upbound.io/v1alpha1
    kind: XSQLInstance
  patchSets:
    - name: providerConfigRef
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.parameters.providerConfigName
    - name: deletionPolicy
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
    - name: region
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.parameters.region
  resources:
    - name: xsqlinstance
      base:
        apiVersion: azure.platform.upbound.io/v1alpha1
        kind: XSQLInstance
      patches:
        - type: PatchSet
          patchSetName: providerConfigRef
        - type: PatchSet
          patchSetName: deletionPolicy
        - type: PatchSet
          patchSetName: region
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.parameters.storageGB
        - fromFieldPath: spec.parameters.passwordSecretRef.namespace
          toFieldPath: spec.parameters.passwordSecretRef.namespace
        - fromFieldPath: spec.parameters.passwordSecretRef.name
          toFieldPath: spec.parameters.passwordSecretRef.name
        - fromFieldPath: spec.parameters.passwordSecretRef.key
          toFieldPath: spec.parameters.passwordSecretRef.key
        - fromFieldPath: metadata.name
          toFieldPath: spec.parameters.networkRef.id
        - fromFieldPath: spec.parameters.engine
          toFieldPath: spec.compositionSelector.matchLabels[dbengine]
          transforms:  # NOTE(ytsarev): to be removed when azure-database consolidate on 'postgres' selector in next release
            - type: map
              map:
                mariadb: mariadb
                postgres: postgresql
      connectionDetails:
        - type: FromConnectionSecretKey
          name: host
          fromConnectionSecretKey: host
        - type: FromConnectionSecretKey
          name: username
          fromConnectionSecretKey: username
        - type: FromConnectionSecretKey
          name: password
          fromConnectionSecretKey: password
        - type: FromConnectionSecretKey
          name: port
          fromConnectionSecretKey: port
    - name: xnetwork
      base:
        apiVersion: azure.platform.upbound.io/v1alpha1
        kind: XNetwork
      patches:
        - type: PatchSet
          patchSetName: region
        - type: PatchSet
          patchSetName: providerConfigRef
        - type: PatchSet
          patchSetName: deletionPolicy
        - fromFieldPath: metadata.name
          toFieldPath: spec.parameters.id
