apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-dbaas
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-dbaas
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The configuration-dbaas configuration provides abstraction over multicloud
      database instance management.
    meta.crossplane.io/readme: |
      The configuration-dbaas bundles the single API that allows unified multicloud
      provisioning of fully managed database instances.
      Deploy most popular database services using the same consistent Claim spec.

spec:
  crossplane:
    version: ">=v1.13.2-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-database
      version: ">=v0.1.0"
    - configuration: xpkg.upbound.io/upbound/configuration-azure-database
      version: ">=v0.2.0"
